const CONSTANTS = {
  BAD_REQUEST: 'BAD REQUEST',
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  NOT_FOUND: "NOT FOUND",
  NOT_AUTHORIZATION: "NOT_AUTHORIZATION",
  NOT_AUTHENTICATION: "NOT_AUTHENTICATION",

  HTTP_CODE: {
    BAD_REQUEST: 400,
    SUCCESS: 200,
    ERROR: 500,
    NOT_AUTHORIZATION: 403,
    NOT_AUTHENTICATION: 401,
    NOT_FOUND_ERR: 404,
  },
};

module.exports = {
    CONSTANTS
}